# Hyperparamètres principaux
"LR": 2.5e-4  # Taux d'apprentissage
"NUM_ENVS": 16  # Nombre d'environnements parallèles
"NUM_STEPS": 128  # Nombre d'étapes par environnement avant une mise à jour
"TOTAL_TIMESTEPS": 1e6  # Nombre total de pas d'entraînement
"UPDATE_EPOCHS": 4  # Nombre d'itérations d'optimisation par mise à jour
"NUM_MINIBATCHES": 4  # Nombre de mini-batchs par mise à jour

# Hyperparamètres du RL
"GAMMA": 0.99  # Facteur de discount pour la récompense future
"GAE_LAMBDA": 0.95  # Facteur de pondération pour GAE (Generalized Advantage Estimation)
"CLIP_EPS": 0.2  # Facteur de clipping pour PPO
"ENT_COEF": 0.01  # Coefficient de l'entropie pour encourager l'exploration
"VF_COEF": 0.5  # Coefficient de pondération pour la perte de Critic
"MAX_GRAD_NORM": 0.5  # Clip des gradients pour éviter les explosions de gradients

# Activation et Architecture du Réseau
"ACTIVATION": "tanh"  # Fonction d'activation utilisée ("relu" ou "tanh")

# Nom et paramètres de l'environnement
"ENV_NAME": "warehouse_management"  # Nom de l'environnement
"ENV_KWARGS": {}  # Arguments optionnels pour l'environnement

# Gestion du Learning Rate
"ANNEAL_LR": True  # Diminution progressive du Learning Rate

# Initialisation du seed aléatoire
"SEED": 30  # Seed de reproductibilité
"NUM_SEEDS": 10  # Nombre de runs avec des seeds différentes

# WandB Configuration (pour tracking des expériences)
"ENTITY": ""  # Organisation ou utilisateur WandB
"PROJECT": "jaxmarl-warehouse"  # Projet WandB
"WANDB_MODE": "disabled"  # Activer ("online") ou désactiver ("disabled") WandB
